sudo: required
language: generic

services:
  - docker:

# before_install:
#   - docker build -t seongbo5230/fib-workflow-test -f ./client/Dockerfile.dev ./client
#
# script:
#   - docker run -e CI=true seongbo5230/fib-workflow-test npm test

after_success:
  - docker build -t seongbo5230/fib-workflow-client ./client
  - docker build -t seongbo5230/fib-workflow-server ./server
  - docker build -t seongbo5230/fib-workflow-worker ./worker
  - docker build -t seongbo5230/fib-workflow-nginx ./nginx
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push seongbo5230/fib-workflow-client
  - docker push seongbo5230/fib-workflow-server
  - docker push seongbo5230/fib-workflow-worker
  - docker push seongbo5230/fib-workflow-nginx

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: fib-workflow
  env: FibWorkflow-env
  bucket_name: elasticbeanstalk-us-west-1-946811956022
  bucket_path: fib-workflow
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
